# Generated by Django 5.1.9 on 2025-05-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="account_type",
            field=models.CharField(
                choices=[("personal", "Personal"), ("accountant", "Accountant")],
                default="personal",
                help_text="Tipo de cuenta: personal o contador.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="pro_features",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el usuario tiene acceso global a funcionalidades Pro (ej: contador pro).",
            ),
        ),
    ]
