# Generated by Django 5.1.9 on 2025-06-28 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_organization_fields'),
        ('accounts', '0003_user_pro_features_list_user_pro_trial_until'),
    ]

    operations = [
    ]
