# Generated by Django 5.1.9 on 2025-06-17 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ASSET", "Activo"),
                            ("LIABILITY", "Pasivo"),
                            ("EQUITY", "Patrimonio"),
                            ("INCOME", "Ingreso"),
                            ("EXPENSE", "Gasto"),
                            ("BANK", "Cuenta Bancaria"),
                            ("CREDIT", "Tarjeta de Crédito"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "functional_type",
                    models.CharField(
                        choices=[
                            ("BANK", "Cuenta Bancaria"),
                            ("CREDIT_CARD", "Tarjeta de Crédito"),
                            ("WALLET", "Billetera Digital"),
                            ("CASH", "Efectivo"),
                            ("OTHER", "Otro"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="organizations.organization",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="chartofaccounts.account",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
                "unique_together": {("code", "organization")},
            },
        ),
    ]
