# Generated by Django 5.1.9 on 2025-06-17 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chartofaccounts", "0001_initial"),
        ("organizations", "0001_initial"),
        ("transactions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("saving", "Saving"),
                            ("debt_payoff", "Debt Payoff"),
                            ("investment", "Investment"),
                            ("purchase", "Purchase"),
                            ("income", "Income"),
                            ("expense_reduction", "Expense Reduction"),
                            ("emergency_fund", "Emergency Fund"),
                            ("retirement", "Retirement"),
                            ("education", "Education"),
                            ("vacation", "Vacation"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("target_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "current_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("start_date", models.DateField()),
                ("target_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("progress_percentage", models.FloatField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("completion_date", models.DateField(blank=True, null=True)),
                ("ai_confidence", models.FloatField(blank=True, null=True)),
                ("ai_recommendations", models.TextField(blank=True, null=True)),
                (
                    "ai_risk_assessment",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "reminder_frequency",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("last_reminder_sent", models.DateTimeField(blank=True, null=True)),
                (
                    "attachments",
                    models.FileField(
                        blank=True, null=True, upload_to="goal_attachments/"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="organizations.organization",
                    ),
                ),
                (
                    "related_accounts",
                    models.ManyToManyField(blank=True, to="chartofaccounts.account"),
                ),
                ("tags", models.ManyToManyField(blank=True, to="transactions.tag")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GoalContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("date", models.DateField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to="goals.financialgoal",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transactions.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="GoalMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("target_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("target_date", models.DateField()),
                ("completed", models.BooleanField(default=False)),
                ("completed_date", models.DateField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="goals.financialgoal",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "target_date"],
            },
        ),
        migrations.AddIndex(
            model_name="financialgoal",
            index=models.Index(
                fields=["organization", "type"], name="goals_finan_organiz_6fb8c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialgoal",
            index=models.Index(
                fields=["target_date"], name="goals_finan_target__043779_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goalcontribution",
            index=models.Index(
                fields=["goal", "date"], name="goals_goalc_goal_id_042e1c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="goalmilestone",
            unique_together={("goal", "order")},
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='not_started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='accounts.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
