# Generated by Django 5.1.9 on 2025-06-17 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0001_initial"),
    ]

    operations = []
