# Generated by Django 5.1.9 on 2025-06-28 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_add_organization_fields"),
    ]

    operations = []
